import { app, BrowserWindow, nativeImage, shell } from 'electron';
import { join } from 'node:path';
import { USE_OPENMYST, OPENMYST_DEEP_LINK_SCHEME } from '@shared/flags';
import { registerIpcHandlers } from './ipc';
import { attachContextMenu } from './context-menu';
import { completeSignInFromUrl, initAuth } from './features/auth';
import { initMe } from './features/me';
import { initUpdater } from './features/updater';
import { log } from './platform';

const isDev = !app.isPackaged;

/**
 * Path to the runtime icon. In prod the packaged `.icns`/`.ico` generated by
 * electron-builder is used automatically — this only matters for dev mode,
 * where otherwise you see the generic Electron icon in the dock/taskbar.
 * `__dirname` is `out/main` at build time; climb two levels to reach
 * `res/logos/`.
 */
const DEV_ICON_PATH = join(__dirname, '../../res/logos/OpenMyst.png');

let mainWindow: BrowserWindow | null = null;

function createMainWindow(): BrowserWindow {
  const win = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1000,
    minHeight: 640,
    show: false,
    backgroundColor: '#0f1115',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    // macOS ignores BrowserWindow.icon (it uses the bundle). Windows + Linux
    // pick it up here; both cases are only relevant in dev — in prod the
    // icon is baked into the installer by electron-builder.
    ...(isDev && process.platform !== 'darwin' ? { icon: DEV_ICON_PATH } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      spellcheck: true,
    },
  });

  attachContextMenu(win);

  win.once('ready-to-show', () => {
    win.show();
    if (isDev) win.webContents.openDevTools({ mode: 'right' });
  });

  // Null the module-level handle when the window goes away so `focusMainWindow`
  // and other callers don't touch a destroyed BrowserWindow — that throws
  // "Object has been destroyed" from native code and crashes the main process
  // (seen when the OS re-delivers a deep link or `second-instance` fires
  // after the user closed the window on macOS).
  win.on('closed', () => {
    if (mainWindow === win) mainWindow = null;
  });

  win.webContents.on('preload-error', (_event, preloadPath, error) => {
    console.error('[preload-error]', preloadPath, error);
  });
  win.webContents.on('render-process-gone', (_event, details) => {
    console.error('[render-process-gone]', details);
  });

  win.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: 'deny' };
  });

  const devUrl = process.env['ELECTRON_RENDERER_URL'];
  if (isDev && devUrl) {
    void win.loadURL(devUrl);
  } else {
    void win.loadFile(join(__dirname, '../renderer/index.html'));
  }

  mainWindow = win;
  return win;
}

/**
 * Register the `openmyst://` deep-link scheme so the OS hands URLs starting
 * with it back to this process. Only needed in managed mode — BYOK dev flow
 * doesn't round-trip through the browser for auth.
 *
 * In dev the second argument points Electron at the actual electron binary
 * so the OS can find a running instance to notify. In a packaged build
 * electron-builder already wires up the scheme via electron-builder.yml.
 */
function registerDeepLinkScheme(): void {
  if (!USE_OPENMYST) return;
  if (isDev && process.platform === 'win32') {
    // On Windows, dev-mode registration needs the path to the electron
    // binary + the entry script; otherwise the OS has nothing to launch.
    app.setAsDefaultProtocolClient(OPENMYST_DEEP_LINK_SCHEME, process.execPath, [
      join(__dirname, '..', '..'),
    ]);
  } else {
    app.setAsDefaultProtocolClient(OPENMYST_DEEP_LINK_SCHEME);
  }
}

function focusMainWindow(): void {
  if (!mainWindow || mainWindow.isDestroyed()) {
    // Window was closed (common on macOS where the app keeps running with no
    // windows). Re-create it instead of silently no-oping — the caller is
    // almost always "user clicked the dock icon" or "deep link came in".
    createMainWindow();
    return;
  }
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.focus();
}

async function handleDeepLink(url: string): Promise<void> {
  if (!USE_OPENMYST) return;
  log('auth', 'deepLink.received', { preview: url.slice(0, 80) });
  const ok = await completeSignInFromUrl(url);
  log('auth', 'deepLink.handled', { ok });
  focusMainWindow();
}

/**
 * macOS delivers deep links via the `open-url` event. Must be attached
 * BEFORE `app.whenReady` because the OS can fire `open-url` while the app
 * is still starting (it's what launched us in the first place).
 */
app.on('open-url', (event, url) => {
  event.preventDefault();
  void handleDeepLink(url);
});

/**
 * Single-instance lock — critical for deep-link handling on Windows/Linux.
 * A second launch (triggered by the OS when the browser hits
 * `openmyst://auth-callback…`) will fail the lock, which fires
 * `second-instance` on the already-running primary with the URL as argv.
 */
if (USE_OPENMYST) {
  const gotLock = app.requestSingleInstanceLock();
  if (!gotLock) {
    app.quit();
  } else {
    app.on('second-instance', (_event, argv) => {
      const urlArg = argv.find((a) => a.startsWith(`${OPENMYST_DEEP_LINK_SCHEME}://`));
      if (urlArg) void handleDeepLink(urlArg);
      focusMainWindow();
    });
  }
}

registerDeepLinkScheme();

void app.whenReady().then(async () => {
  // macOS uses the bundle icon in prod. In dev without this, the dock shows
  // the generic Electron logo; setIcon paints our brand immediately.
  if (isDev && process.platform === 'darwin' && app.dock) {
    try {
      const img = nativeImage.createFromPath(DEV_ICON_PATH);
      if (!img.isEmpty()) app.dock.setIcon(img);
    } catch {
      // Icon is cosmetic in dev; never block startup on it.
    }
  }

  await initAuth();
  await initMe();
  registerIpcHandlers();
  createMainWindow();
  initUpdater();

  // On launch, check whether the process was started with a deep-link URL
  // in argv (Windows/Linux cold-start path).
  if (USE_OPENMYST) {
    const urlArg = process.argv.find((a) => a.startsWith(`${OPENMYST_DEEP_LINK_SCHEME}://`));
    if (urlArg) void handleDeepLink(urlArg);
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createMainWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
