import { app, BrowserWindow, nativeImage, shell } from 'electron';
import { join } from 'node:path';
import { registerIpcHandlers } from './ipc';
import { attachContextMenu } from './context-menu';

const isDev = !app.isPackaged;

/**
 * Path to the runtime icon. In prod the packaged `.icns`/`.ico` generated by
 * electron-builder is used automatically — this only matters for dev mode,
 * where otherwise you see the generic Electron icon in the dock/taskbar.
 * `__dirname` is `out/main` at build time; climb two levels to reach
 * `res/logos/`.
 */
const DEV_ICON_PATH = join(__dirname, '../../res/logos/OpenMyst.png');

function createMainWindow(): BrowserWindow {
  const win = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1000,
    minHeight: 640,
    show: false,
    backgroundColor: '#0f1115',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    // macOS ignores BrowserWindow.icon (it uses the bundle). Windows + Linux
    // pick it up here; both cases are only relevant in dev — in prod the
    // icon is baked into the installer by electron-builder.
    ...(isDev && process.platform !== 'darwin' ? { icon: DEV_ICON_PATH } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      spellcheck: true,
    },
  });

  attachContextMenu(win);

  win.once('ready-to-show', () => {
    win.show();
    if (isDev) win.webContents.openDevTools({ mode: 'right' });
  });

  win.webContents.on('preload-error', (_event, preloadPath, error) => {
    console.error('[preload-error]', preloadPath, error);
  });
  win.webContents.on('render-process-gone', (_event, details) => {
    console.error('[render-process-gone]', details);
  });

  win.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: 'deny' };
  });

  const devUrl = process.env['ELECTRON_RENDERER_URL'];
  if (isDev && devUrl) {
    void win.loadURL(devUrl);
  } else {
    void win.loadFile(join(__dirname, '../renderer/index.html'));
  }

  return win;
}

void app.whenReady().then(() => {
  // macOS uses the bundle icon in prod. In dev without this, the dock shows
  // the generic Electron logo; setIcon paints our brand immediately.
  if (isDev && process.platform === 'darwin' && app.dock) {
    try {
      const img = nativeImage.createFromPath(DEV_ICON_PATH);
      if (!img.isEmpty()) app.dock.setIcon(img);
    } catch {
      // Icon is cosmetic in dev; never block startup on it.
    }
  }

  registerIpcHandlers();
  createMainWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createMainWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
